### ISSUE TITLE
Hyperlink from readme to janztec.com site is wrong

### ISSUE THREAD

**Issue by vovanp** [janztec/empc-cxplus-linux-drivers#1]
I've tried to follw the link [https://www.janztec.com/en/products/embedded-computing/embedded-pc/empc-cx/](https://www.janztec.com/en/products/embedded-computing/embedded-pc/empc-cx/) and have an 404 error:   
Sorry, der Link existiert nicht.

**Comment by janztec-ama** [comment]
That's right. We have had a major website overhaul a couple of weeks ago and I had not updated the links on github. Thanks for the notification!
